### ISSUE TITLE
PyPI pysdm name clash

### ISSUE THREAD

**Issue by slayoo** [michaelxusc/testing-python-packages#1]
Hello, 

Not sure where to best raise this point, but let me try here :)
Together with @piotrbartman, @Golui and other developers of https://github.com/atmos-cloud-sim-uj/PySDM, we intend to publish a PyPI PySDM package. There is an obvious name clash with an empty https://pypi.org/project/pysdm entry by https://pypi.org/user/michaelxusc 
 
Please respond here with any hints if the existing PyPI pysdm entry is planned to be populated/maintained?

Thanks,
Sylwester

**Comment by michaelxusc** [comment]
@slayoo apologies for the late response. Feel free to take the package name as you already have. We took a short-term step to reserve specific package names as an initial mitigation for: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610.
